### ISSUE TITLE
Recon Hides and Fighting Positions

### ISSUE THREAD

**Issue by DEL-J** [Diffusion9/Sandbox.Stratis#35]
Recon hides should be persistent and flagged on the map in the same way that bases are flagged, with the platoon color and an identifier. Players should not spawn at these positions, but players should have to dismantle the positions in order to redeploy them, just like any other base.

Fighting positions don't need to be marked or persistent.

**Comment by jmlane** [comment]
Unfamiliar with the current fortification/object placement scripts, so waiting on @Diffusion9's feedback.

Sounds like a reasonable limitation. Not super fond of auto-marking the map, especially for individual placements, unless personal markers are possible.

**Comment by Diffusion9** [comment]
This is already implemented in the code, but is [porpously](http://idontseatheporpoiseinthis.weebly.com/uploads/2/6/0/1/26012442/136029_orig.jpg) disabled due to some bugs.

Originally I was under the assumption based on some previous discussion that the fighting positions would not have any map markings but the recon hides would -- fighting positions could be deployed by pretty much everybody, but recon hides had a specific list, and were much less numerous.

As I mentioned above the system is there, but disabled: In the system currently implemented in the live build, the fighting positions and recon hides are just another 'base' in the base deployment system, so the 'bugs' are that: 1) You can only deploy one of either of them, 2) an error when deploying because they have no marker data.

But since I'm starting to dislike the base deployment system more and more as the days go on I'll probably eventually redesign whats there anyways, and make it a bit less of a bodge job, so I will keep this enhancement in mind when doing that.

**Comment by Diffusion9** [comment]
Now implemented as of 043b0b6.
